use std::fs;
use std::process::Command;

mod common;

use common::{BINARY_NAME, setup};

#[test]
fn test_input_file_ok() {
    // given
    let ctx = setup();
    let txt_file = ctx.get_path().join("foo.txt");
    fs::write(
        &txt_file,
        // 0x68 0x65..0x6C 0x64
        "hello world",
    )
    .unwrap();

    // when
    let mut bs = Command::new(BINARY_NAME);
    let cmd = bs.arg("enc").arg(&txt_file.to_str().unwrap());

    // then
    let output = cmd.output().unwrap();
    assert!(output.status.success());
    let stdout = str::from_utf8(&output.stdout).unwrap();
    // h e..ld
    assert!(stdout.contains("Read bytes: 0x68 0x65..0x6C 0x64"), "stdout:\n---{}\n---", stdout);
    // d'h'..r'l'
    assert!(stdout.contains("Generated bytes: 0x32 0x34..0x39 0x36"), "stdout:\n---{}\n---", stdout);
}

#[test]
fn test_input_file_wrong() {
    // given
    let ctx = setup();
    let txt_file = ctx.get_path().join("foo.txt");
    fs::write(&txt_file, "hello world").unwrap();

    // when: wrong file
    let mut bs = Command::new(BINARY_NAME);
    let cmd = bs.arg("enc").arg(ctx.get_path().join("bar.txt"));

    // then
    let output = cmd.output().unwrap();
    assert!(!output.status.success());
    let stderr = str::from_utf8(&output.stderr).unwrap();
    assert!(stderr.contains("Invalid path"));
}
