use std::path::PathBuf;
use std::fs;

mod input;
mod swap;
mod util;

use swap::{swap_bytes};
use util::{init_logger, Verbosity};

// secondary export: signature (can be used to verify the file, by tests, etc)
pub use util::signature::SIGNATURE;

// secondary exports: to be used by main.rs
pub use input::{CypherCli, CypherCommand};

// secondary export: can be used by a 3rd party CLI to log more stuff
pub use util::logger;

// main export: shuffle_bytes
pub fn shuffle_bytes(
    command: CypherCommand,
    file_path: PathBuf,
    overwrite: bool,
    verbosity: Verbosity
) {
    init_logger(verbosity);
    let logger = logger();

    let mut file_bytes =
        fs::read(&file_path).unwrap_or_else(|_| panic!("Could not read file {:?}", &file_path));

    if file_bytes.is_empty() {
        logger.err("No Bytes could be read from file. Doing nothing");
        return;
    }

    logger.log("Read bytes: ");
    logger.log_bytesn(&file_bytes);

    file_bytes = swap_bytes(file_bytes, &command);

    logger.log("Generated bytes: ");
    logger.log_bytesn(&file_bytes);

    if overwrite {
        fs::write(&file_path, file_bytes)
            .unwrap_or_else(|_| panic!("Could not write to file: {:?}", &file_path));
    }
}