use std::fs;

mod input;
mod swap;
mod util;

use clap::Parser;
use input::{CypherCli, CypherCommand};
use swap::{SwappingDirection, swap_bytes};
use util::{init_logger, logger};

fn main() {
    let CypherCli {
        command,
        file_path,
        overwrite,
        verbosity,
    } = CypherCli::parse();
    init_logger(verbosity);
    let logger = logger();

    let mut file_bytes =
        fs::read(&file_path).expect(&format!("Could not read file {:?}", &file_path));

    if file_bytes.is_empty() {
        logger.err("No Bytes could be read from file. Doing nothing");
        return;
    }
    println!("Bytes raw println!: {:?}", &file_bytes);

    logger.log("Read bytes: ");
    logger.log_bytesn(&file_bytes);

    file_bytes = match command {
        CypherCommand::Enc => swap_bytes(file_bytes, SwappingDirection::Right),
        CypherCommand::Dec => swap_bytes(file_bytes, SwappingDirection::Left),
    };

    logger.log("Generated bytes: ");
    logger.log_bytesn(&file_bytes);

    if overwrite {
        fs::write(&file_path, file_bytes)
            .expect(&format!("Could not write to file: {:?}", &file_path));
    }
}
